name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # Bước 3: Cài đặt các dependency
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # Bước 4: Build và chạy unit tests
      - name: Build & Unit Tests
        run: ./gradlew testDebugUnitTest

      # Bước 5: Chạy instrumented tests trên emulator
      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest
